### ISSUE TITLE
Set Default Window Size to Fit Everything on One Line

### ISSUE THREAD

**Issue by kaiwolf26** [wolfpaq/keyword-clip#15]
![Screen Shot 2020-06-30 at 10 02 48 AM](https://user-images.githubusercontent.com/67557241/86155506-5706c900-bab9-11ea-8be1-3ba359b98e63.png)

It would be nice if on launch the default window size had all the fields in the filenaming window in a line rather than two lines like it is now.

**Comment by wolfpaq** [comment]
I changed the layout of that section to have better wrapping behavior on window sizing and then set the default width and height to contain all the controls without scrolling.
