### ISSUE TITLE
Category Search Doesn't Search SubCategory

### ISSUE THREAD

**Issue by kaiwolf26** [wolfpaq/keyword-clip#21]
Looks like typing the category and sub category doesn't pull up the result

**Comment by wolfpaq** [comment]
It should work if you don't put any space between the category and subcategory. Maybe I should strip spaces from what the user types in before doing the search. I currently only strip spaces from the beginning and end of what they type in.

**Comment by kaiwolf26** [comment]
Yeah, I think that would be a good idea. I wasn't able to figure that out on my own

**Comment by wolfpaq** [comment]
I changed how search is done. I think it should work more the way you expect when you add spaces in category/subcategory searches. I'm going to assign it back to you. If you like the way it works, go ahead and close it. Otherwise just assign it back to me with your comments.

**Comment by wolfpaq** [comment]
This is working as expected so I'm going to close it.
