### ISSUE TITLE
Spreadsheet was updated

### ISSUE THREAD

**Issue by kaiwolf26** [wolfpaq/keyword-clip#24]
https://docs.google.com/spreadsheets/d/1qY93Ssx45YLKPyZQoOz9Fe9vweAJrURK88ajkDevvLE/edit#gid=1228434045

Looks like the inclusion of "-" in words like Sci-Fi were causing other software to get messed up, so we removed any -'s from categories and subcategories.

**Comment by kaiwolf26** [comment]
This is still open, but it looks like we found another typo today as a heads up. It's been updated on the link

**Comment by wolfpaq** [comment]
Just pulled the latest one and put it in as the default.
