### ISSUE TITLE
Change Names of Sections in Filename Tab

### ISSUE THREAD

**Issue by kaiwolf26** [wolfpaq/keyword-clip#25]
Change User Category to "CreatorID"
Change Show Name to "SourceID"

**Comment by wolfpaq** [comment]
Updated in version 1.0.1

**Comment by wolfpaq** [comment]
It's actually the "User Initials" that should be changed to "CreatorID". I reopened this to fix that up.

**Comment by wolfpaq** [comment]
Done in version 1.0.1
