### ISSUE TITLE
Add Optional "Vendor Category" to Filename Builder

### ISSUE THREAD

**Issue by kaiwolf26** [wolfpaq/keyword-clip#26]
We've added a custom field for vendors to use called "vendor category"

It belongs between the first underscore and filename delineated by a '-'

ie. CatID-UserCategory_VendorCategory-FXName_CreatorID(_formerly user initials_)_SourceID(_formerly show_)_UserData

**Comment by wolfpaq** [comment]
Is that a required field or optional?

**Comment by kaiwolf26** [comment]
Optional!

**Comment by wolfpaq** [comment]
I just noticed it said optional in the title of the bug :)

**Comment by wolfpaq** [comment]
SInce we changed "User Category" to "CreatorID" I'm thinking this new one should be called "VendorID" for consistency. Let me know if you think that is wrong an it should be "Vendor Category".

**Comment by wolfpaq** [comment]
Done in version 1.0.1
